version: '2'
services:
  postgres:
    container_name: consent-db-postgres
    image: launcher.gcr.io/google/postgresql10
    environment:
      "POSTGRES_PASSWORD": "consent-api"
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgres/data:/var/lib/postgresql/data
